### ISSUE TITLE
Add safety checks for deleting a Category that has Skills

### ISSUE THREAD

**Issue by brendoncaulkins** [excellaco/tcp-angular#48]
It would be nice to list how many skills a category has in the table, so the Admin knows how many skills they're affecting when a Category is changed.

Also, we need a mechanism to handle deleting a Category when there are still skills under it.

- Are the skills migrated to another Category?
- Are the Skills also deleted?
- Is the user stopped from performing the action?

**Comment by cvliano28** [comment]
> It would be nice to list how many skills a category has in the table, so the Admin knows how many skills they're affecting when a Category is changed.
> 
> Also, we need a mechanism to handle deleting a Category when there are still skills under it.
> 
> * Are the skills migrated to another Category?
> * Are the Skills also deleted?
> * Is the user stopped from performing the action?

From Wyn - Yes we need a mechanism and the preferred option would be to have a Pop up a warning that all skills would be deleted, then delete them all if confirmed

**Comment by brendoncaulkins** [comment]
Perfect, thanks!  I've communicated this to TCP-Java, since it will also impact them.
