### ISSUE TITLE
Enhance Employee List with additional columns

### ISSUE THREAD

**Issue by brendoncaulkins** [excellaco/tcp-angular#59]
Could be cool to use [Material Chips](https://material.angular.io/components/chips/overview) for the skill list in the table.

**Question**:  Which columns should we show?

**Comment by cvliano28** [comment]
> Could be cool to use [Material Chips](https://material.angular.io/components/chips/overview) for the skill list in the table.
> 
> **Question**: Which columns should we show?

From Wyn - No need to add any additional columns unless they exercise some functionality or control not in the app yet, that might be used in a tech challenge.

**Comment by brendoncaulkins** [comment]
In order to support #70 , we'll want to display skills, at a minimum.

IMO, we should make these changes:

-  +Skills (as chips)
-  -Birth Date
-  -Phone Number
